### ISSUE TITLE
org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by shuhaib3** [prayagsingh/docker-jibri-pulseaudio#8]
![image](https://user-images.githubusercontent.com/57085593/134043830-5a6ca06c-961d-4907-9eb8-5c4e072b8c07.png)
getting an error like this in jibri logs. am running jibri in kubernetes,

**Comment by prayagsingh** [comment]
It is trying to connect `https://meet.jitsi` which is not a valid URL. Please checkout the k8s config in examples.

**Comment by shuhaib3** [comment]
@prayagsingh 
am getting a error like this now.
021-09-26 00:45:37.634 INFO: [51] org.jitsi.jibri.selenium.pageobjects.HomePage.log() Visiting url shard.clanmeeting.com
2021-09-26 00:45:37.656 SEVERE: [51] org.jitsi.jibri.selenium.JibriSelenium.log() An error occurred while joining the call
org.openqa.selenium.InvalidArgumentException: invalid argument
  (Session info: chrome=90.0.4430.212)
  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 4.19.0-17-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jibri-0', ip: '10.244.9.253', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.0-17-amd64', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.sIvDZG}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:35253}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 90.0.4430.212, webStorageEnabled: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 4c744e1ff70649f78486f340eb6e6f7a
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
        at org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:35)
        at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:291)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

**Comment by shuhaib3** [comment]
![image](https://user-images.githubusercontent.com/57085593/134784177-9e17c324-5d80-4bbd-a709-032975e902b9.png)

**Comment by prayagsingh** [comment]
What's the value of `PUBLIC_URL`?

**Comment by shuhaib3** [comment]
@prayagsingh same as public domain name.

**Comment by prayagsingh** [comment]
> @prayagsingh same as public domain name.

Try setting PUBLIC_URL to  `https://your_domain.com`. If this is not working then try `hostAlias` in jibri.yml file.

**Comment by shuhaib3** [comment]
> > @prayagsingh same as public domain name.
> 
> Try setting PUBLIC_URL to `https://your_domain.com`. If this is not working then try `hostAlias` in jibri.yml file.
> 
> Also please check the logs.txt/browser_logs.txt for more clear picture about the error.

tried setting both.
recording is getting stopped.
![image](https://user-images.githubusercontent.com/57085593/134806569-86e91f1d-0d7a-4d74-a82e-f6ea3d099715.png)

this is what am getting in browser_logs.txt now.

**Comment by shuhaib3** [comment]
![image](https://user-images.githubusercontent.com/57085593/134807124-b9cfb58f-4869-41af-879f-31d00d70f35f.png)
this is what am getting in console logs of container.

**Comment by shuhaib3** [comment]
it worked now. recorder password was wrong in prosody. Thanks.

**Comment by prayagsingh** [comment]
Closing it since it is working.
