### ISSUE TITLE
Record video timeout 

### ISSUE THREAD

**Issue by riderx** [prayagsingh/docker-jibri-pulseaudio#9]
i have deploy jitsi ans jibri in docker with theses conf.

https://github.com/riderx/lemverse-deploy/tree/main/jitsi

and I got this error
```
2021-09-29 18:59:55.114 INFO: [54] org.openqa.selenium.remote.ProtocolHandshake.createSession() Detected dialect: OSS
2021-09-29 18:59:55.161 INFO: [54] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Writing recording to /config/recordings/ylmhqaiyxwuzbtur, finalize script path /config/finalize.sh
2021-09-29 18:59:55.169 FINE: [54] org.jitsi.jibri.statsd.JibriStatsDClient.log() Incrementing statsd counter: start:recording
2021-09-29 18:59:55.172 INFO: [54] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: IDLE -> BUSY
2021-09-29 18:59:55.173 FINE: [54] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-09-29 18:59:55.174 INFO: [54] org.jitsi.jibri.api.xmpp.XmppApi.log() Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2021-09-29 18:59:55.190 INFO: [54] org.jitsi.jibri.api.xmpp.XmppApi.log() Sending 'pending' response to start IQ
2021-09-29 18:59:55.210 INFO: [66] org.jitsi.jibri.selenium.pageobjects.HomePage.log() Visiting url https://video.indiemakers.space
2021-09-29 19:00:17.019 FINE: [16] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-09-29 19:00:55.271 SEVERE: [66] org.jitsi.jibri.selenium.JibriSelenium.log() An error occurred while joining the call
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: -0.001
  (Session info: chrome=90.0.4430.212)
  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 5.4.0-84-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'fc9634165fe4', ip: '172.21.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-84-generic', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.Pf64Dp}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:34345}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 90.0.4430.212, webStorageEnabled: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f0d98d1a43a4ae68de589c69afe2bf0c
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
        at org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:35)
        at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:291)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-09-29 19:00:55.275 INFO: [66] org.jitsi.jibri.selenium.JibriSelenium.log() Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
2021-09-29 19:00:55.283 INFO: [66] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() File recording service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
2021-09-29 19:00:55.284 INFO: [66] org.jitsi.jibri.api.xmpp.XmppApi.log() Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq <iq to='jibribrewery@internal-muc.meet.jitsi/focus' id='8tLun-56' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
2021-09-29 19:00:55.287 FINE: [66] org
```
Recording start and after 90 sec say it's failing.
I have try many different way and still got issue

**Comment by prayagsingh** [comment]
sorry for the late response, I was busy with some other work. 

Are you still facing this issue?

**Comment by riderx** [comment]
@prayagsingh i understand, yes i still have it

**Comment by prayagsingh** [comment]
> @prayagsingh i understand, yes i still have it

What's the machine config which is running jibri? 
TBH, I'm seeing this kind of error first time.

**Comment by riderx** [comment]
@prayagsingh since the frech install fixed the issue, i did try to do record and after check the jibri machine eat more than 2 Gb of ram in my side, any idea why ?

**Comment by riderx** [comment]
If i revert to v1.4 it's a bit better it goes to max mem slowly but still goes :/

**Comment by prayagsingh** [comment]
> <img width="1001" alt="Screenshot 2021-10-19 at 23 06 21" src="https://user-images.githubusercontent.com/4084527/137997329-759d3e83-b501-41da-a1ff-2463d69a685f.png">
> I have a 4 gb machine but it look to don't be enought :/

Jibri requires min. 4Gb Memory to work properly so you need to run it on a separate machine.

**Comment by prayagsingh** [comment]
> @prayagsingh i doubled the machine size and it's work now, but that insane to consume than much !

Default resolution is set to 1920*1080 hence it requires this much of memory. You can change the resolution to 1280*720.
